---
- name: useradd
  template:
    src: etc/default/useradd.j2
    dest: /etc/default/useradd
    #backup: yes
    mode: 0644
    owner: root
    group: root
  tags:
    - useradd
    - security
...
